runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /font-awesome
  static_dir: font-awesome

- url: /.*
  script: career.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
